adafruit_magtag/magtag.py

add '...' when strings are too long

remove broken ip address print during debug

---

adafruit_magtag/magtag.py

Fixes #9. By moving it to set_text, which is called anyways, this makes the behavior more consistent.

Moved text wrapping to set_text()

---

adafruit_magtag/network.py

Tested using CircuitPython 6.1 beta.1. This has been updated to use the latest Adafruit IO library.

Updated to use latest Adafruit IO

---

adafruit_magtag/graphics.py
adafruit_magtag/magtag.py

avoid accidental exceptions when force-refreshing after, say, updating the background

retry refreshing a few times, let us update faster too

---

adafruit_magtag/magtag.py
adafruit_magtag/network.py

Fixes #22.
Fixes #23.
When there's an unexpected json or your path does not match, this handles it much better. If you have some non-data labels, they can now be specified to not be data, otherwise they are treated as before so it shouldn't break any existing code.

Handle empty json and non-data labels better

---

adafruit_magtag/network.py

It currently handles bad names, but not indices. This fixes it.

Handle bad indices in the json_path

---

adafruit_magtag/magtag.py

This allows developer to receive the index of the textbox which was just created.
Usage:
```
dateBox=magtag.add_text(blahblahblah)
timeBox=magtag.add_text(blahblahblah)
...various code...
magtag.set_text('the date',dateBox)
magtag.set_text('the time',timeBox)
```

return the index of the textbox created by add_text

---

adafruit_magtag/magtag.py
adafruit_magtag/network.py
adafruit_magtag/peripherals.py
adafruit_magtag/wifi_module.py

Fixes #20. This adds the deep and light sleep functions.

Added deep and light sleep functions

---

adafruit_magtag/peripherals.py

The battery voltage multiplier should be 3.3V, not 2.6V, because `AnalogIn` now compensates for the limited voltage range to some extent.
After this fix, the battery voltage is still low by about 0.15V, but I think that's a fix to be made in `AnalogIn`, and will work on that separately.

Fix multiplier for battery voltage

---

adafruit_magtag/graphics.py
adafruit_magtag/magtag.py

Allow for simple setup of rotated display on initialization

you spin me right round baby right round

---

README.rst

PortalBase wasn't listed in README.rst as a dependency

added PortalBase to Dependencies

---

adafruit_magtag/magtag.py

Needed for the sports project because I'm handling this outside the automatic stuff.

Add parameter to allow skipping display autorefresh on fetch

---

adafruit_magtag/peripherals.py

Previously, this would have caused a crash.

Don't let users play a tone equal or less than 0

---

adafruit_magtag/peripherals.py

This might not be used a lot, but this helps in case you need to just load up one bit, and then load up another.

Add deinit function

---

adafruit_magtag/peripherals.py

Fixes #62. This fix addresses the "NEOPIXEL_POWER_INVERTED in use" error. I still was not able to run the example due to the MagTag rebooting, but at least it's not stopping on the Neopixel error now.

Fixed NEOPIXEL_POWER_INVERTED in use on CP 7.0

---

adafruit_magtag/peripherals.py

resolves: #75 
The neopixel library tries to initialize `NEOPIXEL_POWER` pin when you create the Neopixel object. It gracefully handles "pin in use" error.  So we can initialize `NEOPIXEL_POWER` inside of MagTag library before creating the Neopixel object, that way the MagTag library will happen first and keep control of the power pin.
Tested successfully with reproducer code from the issue on MagTag 7.1.0 beta

initialize neopixel power pin before neopixels

---

adafruit_magtag/peripherals.py

I left an issue in the issues section, but decided I could simply make a pull request myself.  (I'm pretty new to the process).
This fix allows a specification of a zero frequency to the play_tone function.
Forum: [https://forums.adafruit.com/viewtopic.php?f=60&t=182821](forum)
Issue: [https://github.com/adafruit/Adafruit_CircuitPython_MagTag/issues/67](issue)

allow tone frequency of 0

---

adafruit_magtag/magtag.py
adafruit_magtag/network.py

Move init of Peripherals() to be done before init of Network() so that board's neopixels are done first, then passed to Network() if status_neopixel uses board.NEOPIXEL. If any other pin is used, it will be passed as is.

Correct use of board.NEOPIXEL as status_neopixel parameter

---

adafruit_magtag/peripherals.py

Added the `BOOT0` button as a fifth pin for the buttons list.
This is dependant on https://github.com/adafruit/circuitpython/pull/6657, where I added the pin's name to the board's port. I'm not sure if the BOOT0 pin was skipped intentionally or not, so I'm opening this as a draft until that PR gets looked at.

Adds `BOOT0` as a fifth pin for the `Peripherals.buttons` list.

---

adafruit_magtag/magtag.py
adafruit_magtag/peripherals.py
docs/examples.rst
examples/magtag_btn_sleep_demo.py

Resolves #64 
Docs now mention that deinit is required in order to use the pins for other things like PinAlarm. 
The new example script is a modified simpletest with idle timeout deep sleep and button wakeup functionality

pin alarm deep sleep example and docs

---

adafruit_magtag/magtag.py

Fixes #86. Autorefresh is true by default to keep behavior roughly the same, though it doesn't refresh until all labels cleared.

Add remove_all_text func that accounts for auto-refresh
